# Generated by Django 4.2.5 on 2024-03-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="author",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="books",
            name="count",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="books",
            name="genre",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="books",
            name="isbn",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="books",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
