# Generated by Django 4.2.5 on 2024-03-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_books_author_books_count_books_genre_books_isbn_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="author",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="books",
            name="genre",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="books",
            name="isbn",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="books",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
