# Generated by Django 4.2.5 on 2024-03-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_alter_books_author_alter_books_genre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="isbn",
            field=models.IntegerField(),
        ),
    ]
