# Generated by Django 5.0.4 on 2024-05-13 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Renewal_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('no_of_days', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YourModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hello1', models.CharField(max_length=100)),
                ('hello2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date_of_admission', models.DateField(null=True)),
                ('subdomain_prefix', models.CharField(default=True, max_length=50)),
                ('booking', models.IntegerField(default=0, verbose_name='Number of Bookings')),
                ('is_active', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('recent_renew_date', models.DateField(null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('renewal_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='routertest.renewal_type')),
            ],
        ),
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=100)),
                ('field2', models.IntegerField()),
                ('yourmodel2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routertest.yourmodel2')),
            ],
        ),
    ]
