# Generated by Django 5.0.4 on 2024-05-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routertest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
